blog/urls.py
from django.urls import include, path
from blog.views import *

app_name='blog'
urlpatterns = [
    path('', PostLV.as_view(), name='index'),
    path('post/', PostLV.as_view(), name='post_list'),
    path('post/<slug:slug>/', PostDV.as_view(), name='post_detail'),
    path('archive/', PostAV.as_view(), name='post_archive'),
    path('<int:year>/', PostYAV.as_view(), name='post_year_archive'),
    path('<int:year>/<str:month>/', PostMAV.as_view(), name='post_month_archive'),
    path('<int:year>/<str:month>/<int:day>/', PostDAV.as_view(), name='post_day_archive'),
    # path('today/', PostTAV.as_view(), name='post_today_archive'),
    path('add/', PostCreateView.as_view(), name='add'),
    # path('post/save/', post_save, name='post_save'),
]

bookmark/urls.py
from django.urls import include, path
from bookmark.views import BookmarkLV, BookmarkDV

app_name='bookmark'
urlpatterns = [
    # Class-based views
    path('', BookmarkLV.as_view(), name='index'),
    path('<int:id>', BookmarkDV.as_view, name='detail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from mysite.views import HomeView
from blog.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostLV.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls', namespace='bookmark')),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from __future__ import unicode_literals # Python 2.x 지원용
from django.utils.encoding import python_2_unicode_compatible
from django.utils.text import slugify

from django.db import models
from django.urls import reverse

# Create your models here.

@python_2_unicode_compatible # Python 2.x 지원용
class Post(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.', blank=True)
    # description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT', blank=True)
    image_type = models.CharField('Image Type', max_length=10, blank=True)
    image = models.ImageField('IMAGE', blank=True)
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'my_post'
        ordering = ('-modify_date',)
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:post_detail', args=(self.slug,))
    
    def get_previous_post(self):
        return self.get_previous_by_modify_date()
    
    def get_next_post(self):
        return self.get_next_by_modify_date()
        
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)

        super(Post, self).save(*args, **kwargs)

bookmark/models.py
from __future__ import unicode_literals # Python 2.x 지원용

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible # Python 2.x 지원용
class Bookmark(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView, TodayArchiveView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

from django.urls import reverse,reverse_lazy

from blog.models import *

# Create your views here.

#--- ListView
class PostLV(ListView) :
    model = Post
    template_name = 'blog/post_all.html'
    context_object_name = 'posts'
    paginate_by = 10

#--- DetailView
class PostDV(DetailView):
    model = Post

#--- ArchiveView
class PostAV(ArchiveIndexView):
    model = Post
    date_field = 'modify_date'

class PostYAV(YearArchiveView):
    model = Post
    date_field = 'modify_date'
    make_object_list = True

class PostMAV(MonthArchiveView):
    model = Post
    date_field = 'modify_date'


class PostDAV(DayArchiveView):
    model = Post
    date_field = 'modify_date'


class PostTAV(TodayArchiveView):
    model = Post
    date_field = 'modify_date'

class PostCreateView(CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'slug', 'content']
    initial = {'slug': 'auto-filling-by-title'}
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form): # self.request
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

# class UploadView(FormView):
#     template_name = 'blog/post_upload.html'
#     context_object_name = 'posts'
#     form_class = Post
#     success_url = ''

#     # def form_valid(self, form):
#     #     # This method is called when valid form data has been POSTed.
#     #     # It should return an HttpResponse.
#     #     form.send_email()
#     #     return super().form_valid(form)

# def post_save(request):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'polls/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

bookmark/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

# Create your views here.

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

mysite/views.py
from django.views.generic.base import TemplateView

# Create your views here

#--- TemplateView
class HomeView(TemplateView):
    template_name = 'blog/post_all.html'

blog/templates/blog/post_all.html
{% extends "base.html" %}

{%block title %}Blog List{% endblock %}

{% block content %}
<style>
    .test1 {
        display: inline-block;
        padding: 10px;
    }
</style>

<div id="content">
    <div>
        <a href="{% url 'blog:add' %}">UPLOAD</a>
    </div>
    {% for post in posts %}
    <div class="test1">
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {{ post.modify_date|date:"N d, Y" }}
        <p>{{ post.description }}</p>
    </div>
    {% endfor %}

    <br />

    <div>
        <span>
            {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_archive.html
<h1>Post Archives until {% now "N d, Y" %}</h1>
<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_year_archive' date|date:'Y' %}">Year-{{ date|date:"Y" }}</a></li>
    {% endfor %}
</ul>

<br/>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_day.html
<h1>Post Archives for {{ day|date:"N d, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_month.html
<h1>Post Archives for {{ month|date:"N, Y" }}</h1>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_archive_year.html
<h1>Post Archives for {{ year|date:"Y" }}</h1>

<ul>
    {% for date in date_list %}
        <li style="display: inline;">
            <a href="{% url 'blog:post_month_archive' year|date:'Y' date|date:'b' %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
</ul>

<br/>

<div>
    <ul>
        {% for post in object_list %}
            <li>{{ post.modify_date|date:"Y-m-d" }}&nbsp;&nbsp;&nbsp;
                <a href="{{ post.get_absolute_url }}"><strong>{{ post.title }}</strong></a>
            </li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/post_detail.html
{% extends "base.html" %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
    // $(function(){
    //     $.ajax({
    //         type: "GET", // 데이터를 전송하는 방법을 지정
    //         url: "http://59.29.224.83:8001", // 통신할 url을 지정
    //         dataType: "json",
    //         success: function (response){ // 통신 성공시
    //             alert(response.message);
    //         }
    //     });
    // });
    // $(".like").click(function () {
    //     var pk = $(this).attr('name')
    //     $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
    //         type: "POST", // 데이터를 전송하는 방법을 지정
    //         url: "{% url 'post:post_like' %}", // 통신할 url을 지정
    //         data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' }, // 서버로 데이터 전송시 옵션
    //         dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
    //         // 서버측에서 전송한 Response 데이터 형식 (json)
    //         // {'likes_count': post.like_count, 'message': message }
    //         success: function (response) { // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경
    //             alert(response.message);
    //             $("#count-" + pk).html(response.like_count + "개");
    //             var users = $("#like-user-" + pk).text();
    //             if (users.indexOf(response.nickname) != -1) {
    //                 $("#like-user-" + pk).text(users.replace(response.nickname, ""));
    //             } else {
    //                 $("#like-user-" + pk).text(response.nickname + users);
    //             }
    //         },
    //         error: function (request, status, error) { // 통신 실패시 - 로그인 페이지 리다이렉트
    //             alert("로그인이 필요합니다.")
    //             window.location.replace("/accounts/login/")
    //             //  alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
    //         },
    //     });
    // })
</script>

{%block title %}{{ object.title }}{% endblock %}

{% block content %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: "GET", // 데이터를 전송하는 방법을 지정
            url: "http://localhost:8000/get_tuna/{{ object.id }}", // 통신할 url을 지정
            dataType: "json",
            success: function (response) { // 통신 성공시
                console.log(response);
                $("#recent_opinion").text(response.opinion);
            },
            error: function (request, status, error) { // 통신 실패시 - 로그인 페이지 리다이렉트
                alert("GET error test"+response)
            },
        });
        $("#add_opinion").click(function () {
            opinion = $("#input_opinion").val();
            $.ajax({
                // contentType: "application/json; charset=UTF-8",
                type: "POST", // 데이터를 전송하는 방법을 지정
                url: "http://localhost:8000/add_opinion", // 통신할 url을 지정
                data: JSON.stringify({ 'id': '{{ object.id }}', 'opinion':opinion, 'csrfmiddlewaretoken': '{{ csrf_token }}' }), // 서버로 데이터 전송시 옵션
                dataType: "json",
                success: function (response) { // 통신 성공시
                    console.log(response);
                    console.log(response);
                    $("#recent_opinion").text(JSON.stringify(response));
                },
                error: function (response) {
                    // alert(response.responseText + response.error)
                    // alert(Object.values(jqXHR))
                }
            });
        });
    });
</script>
<div id="content">
    <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
    <br />

    <div class="body">
        <div>
            {{ object.content|linebreaks }}
        </div>
        <div>
            <p>현재 소견</p>
            <p id="recent_opinion"></p>
        </div>
        <br>
        <div id="div_opinion">
            <p>소견 입력</p>
            <textarea name="" id="input_opinion" cols="30" rows="10"></textarea>
            <input type="button" value="소견 전송" id="add_opinion">
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block title %}Blog 생성 페이지{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/forms.css" %}{% endblock %}

{% block content %}
<div id="content">
    <h1>Post Create/Update - {{ user }} </h1>
    <form action="." method="post">
        {% csrf_token %}

        {% if form.errors %}
            {{ form.errors }}
        {% endif %}

        <p>등록(수정)하고 싶은 Post 작성해 주세요.</p>
        <fieldset class="aligned">
            <div class="form-row">
                {{form.title.label_tag}} {{form.title}}
            </div>
            <div class="form-row">
                {{form.slug.label_tag}} {{form.slug}}
            </div>
            <div class="form-row">
                {{form.description.label_tag}} {{form.description}}
            </div>
            <div class="form-row">
                {{form.content.label_tag}} {{form.content}}
            </div>
        </fieldset>
        <div class="submit-row">
            <input type="submit" value="등록" />
        </div>
    </form>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_detail.html
{% extends "base.html" %}

{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
<div id="content">
    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock %}

bookmark/templates/bookmark/bookmark_list.html
{% extends "base.html" %}

{%block title %}Django Bookmark List{% endblock %}

{% block content %}
<div id="content">
    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <title>{% block title %}Django Web Programming{% endblock %}</title>

    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href='{% static "css/base.css" %}'>
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}">
</head>

<body>
    <div id="header">
        <h2 class="maintitle">Easy&amp;Fast Django Web Programming</h2>
        <h4 class="welcome">Welcome, <a href="#">user name</a>/
            <a href="#">Change Password</a>/
            <a href="#">Logout</a></h4>
    </div>

    <div id="menu">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'bookmark:index' %}">Bookmark</a></li>
        <li><a href="{% url 'blog:index' %}">Blog</a></li>
        <li><a href="#">Photo</a></li>

        <li><a href="#">Add&bigtriangledown;</a>
            <ul>
                <li><a href="#">Bookmark</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
            </ul>
        </li>

        <li><a href="#">Change&bigtriangledown;</a>
            <ul>
                <li><a href="#">Bookmark</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Photo</a></li>
            </ul>
        </li>

        <li><a href="{% url 'blog:post_archive' %}">Archive</a></li>
        <li><a href="#">Search</a></li>
        <li><a href="{% url 'admin:index' %}">Admin</a></li>
    </div>

    {% block content %}{% endblock %}

    {% block footer %}{% endblock %}
</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block title %}home.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "css/home.css" %}{% endblock %}

{% block content %}
<div id="content_home">
    <div id="homeimg">
        <a href="/"><img src="{% static 'img/django-actor-big.jpg' %}" style="height:256px;"/></a>
        <h4 style="margin: 0;">This is Django powered web site.</h4>
    </div>

    <hr style="margin: 5px 0;">

    <h2>Select Application</h2>

    <table id="applist">
        <tr>
            <td><b><i><a href="{% url 'bookmark:index' %}">Bookmark</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="{% url 'blog:index' %}">Blog</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
        <tr>
            <td><b><i><a href="#">Photo</a></i></b></td>
            <td>You can write your own post and share to others. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo</td>
            <td class="Edit"><i><a href="#">Add</a></i></td>
            <td class="Edit"><i><a href="#">Change</a></i></td>
        </tr>
    </table>
</div>
{% endblock content %}

{% block footer %}
<div id="footer">
    &copy; user 2018
</div>
{% endblock footer %}